name: repo_annotation
description: Repository class code generation.
version: 0.0.1
homepage: https://github.com/SunnatilloShavkatov/repo_annotation.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

